import type {
  EventCategory,
  EventCategoryFormData,
} from '~/domain/entities/event-category'

/**
 * Repository contract for the master `event_categories` table.
 *
 * The list endpoint intentionally has no pagination — the admin is
 * expected to keep the total number of categories small (a few
 * dozen at most), and a single `select` keeps the UI simple.
 */
export interface EventCategoryRepository {
  /** Returns every category, ordered by name ascending. */
  list(): Promise<EventCategory[]>

  /** Look up a single category by its id, or `null` if missing. */
  getById(id: string): Promise<EventCategory | null>

  /**
   * Insert a new category. The id is generated by the repository
   * to keep the `CAT-YYYY-NNNNN` format consistent. Throws when
   * the name already exists (unique violation).
   */
  create(input: EventCategoryFormData): Promise<EventCategory>

  /** Update name/detail of an existing category. */
  update(id: string, input: EventCategoryFormData): Promise<EventCategory>

  /**
   * Delete a category. Throws when at least one event still
   * references it (the FK uses `ON DELETE RESTRICT`). The use case
   * catches that case and surfaces a friendly error message.
   */
  delete(id: string): Promise<void>
}
