import type {
  Registration,
  RegistrationStatus,
  RegistrationWithEvent,
  RegistrationWithUser,
} from '~/domain/entities/registration'

/**
 * Filter for attendance aggregation queries.
 * - `{ kind: 'all' }`                  → all time
 * - `{ kind: 'day', date: 'YYYY-MM-DD' }` → only events whose
 *   `event.date` falls on that calendar date
 * - `{ kind: 'year', year: 2026 }`     → only events whose
 *   `event.date` is in that year
 */
export type AttendancePeriod =
  | { kind: 'all' }
  | { kind: 'day'; date: string }
  | { kind: 'year'; year: number }

export interface RegistrationWithUserAndEvent extends Registration {
  user: RegistrationWithUser['user']
  event: RegistrationWithEvent['event']
}

export interface RegistrationListParams {
  eventId?: string
  userId?: string
  status?: RegistrationStatus
  search?: string
  limit?: number
  offset?: number
}

export interface AttendanceSummary {
  user: RegistrationWithUser['user']
  totalHadir: number
  totalRegistrasi: number
}

export interface RegistrationRepository {
  /**
   * Returns all registrations (most recent first). Used by the
   * admin registration list page when no filters are applied.
   */
  getAll(params?: RegistrationListParams): Promise<RegistrationWithUser[]>

  /**
   * Fetches a single registration by id. Returns null if not found.
   */
  getById(id: string): Promise<Registration | null>

  /**
   * Returns the existing registration for a (userId, eventId) pair,
   * or null if the user has not registered for the event.
   *
   * NOTE: Sejak migration #6 SELECT langsung ke `event_registrations`
   * sudah diblokir untuk `anon` (lihat
   * `event_registrations_block_direct_select` di migration #6). Method ini
   * jadi HANYA aman dipakai dalam konteks admin (authenticated dengan
   * `app_metadata.role='admin'`). Untuk alur publik
   * [`BookEvent`](application/use-cases/book-event.ts), gunakan
   * `RegistrationRepository.existsByUserAndEvent` yang melalui RPC
   * `find_registration_by_user_and_event`.
   */
  findByUserAndEvent(
    userId: string,
    eventId: string,
  ): Promise<Registration | null>

  /**
   * Cek keberadaan registrasi untuk (userId, eventId). Return boolean.
   *
   * Dipakai oleh [`BookEvent`](application/use-cases/book-event.ts) yang
   * butuh cek duplikat di alur publik (form booking tanpa login).
   * Karena SELECT langsung ke `event_registrations` sudah diblokir
   * untuk `anon` (migration #6), method ini memakai RPC
   * `find_registration_by_user_and_event` yang `SECURITY DEFINER`.
   */
  existsByUserAndEvent(userId: string, eventId: string): Promise<boolean>

  /**
   * Inserts a new registration. The id is generated by the repository
   * ('REG-YYYY-NNNNN'). Throws when (userId, eventId) is duplicated
   * (unique constraint enforced at the DB level).
   */
  create(input: { userId: string; eventId: string }): Promise<Registration>

  /**
   * Updates the registration status. Automatically sets
   * `checkin_at = now()` when the new status is 'Hadir', and clears
   * it when the status rolls back to 'Terdaftar'.
   *
   * `verifiedByEmail` (optional, default null) is the email of the
   * admin who performed the verification — it is recorded in the
   * `verified_by_email` + `verified_at` columns (migration #5) as
   * an audit trail. When null, the audit columns are cleared if the
   * status rolls back to 'Terdaftar', or simply skipped otherwise.
   */
  updateStatus(
    id: string,
    status: RegistrationStatus,
    verifiedByEmail?: string | null,
  ): Promise<Registration>

  delete(id: string): Promise<void>

  countByEvent(eventId: string): Promise<number>

  /**
   * Lists every registration of a user with the event relation
   * hydrated (`event:events(*)`). Result is sorted by `event.date`
   * descending, with `registered_at` descending as a tie-breaker.
   */
  listByUserWithEvent(userId: string): Promise<RegistrationWithEvent[]>

  /**
   * Aggregates attendance counts (`status = 'Hadir'`) per member.
   *
   * Output contains a summary per user with the user object,
   * totalHadir, and totalRegistrasi. It can be filtered with
   * `period` (see `AttendancePeriod`).
   *
   * Implementation: SELECT join `event_registrations` → `events` →
   * `event_users`, aggregate `count(*) filter (where status='Hadir')`
   * per `user_id`, then hydrate `user:event_users(*)`. Results are
   * sorted by `totalHadir` DESC (most first), with `nama` ASC as
   * tie-breaker for stable display.
   */
  getAttendanceByUser(period: AttendancePeriod): Promise<AttendanceSummary[]>

  /**
   * Lists all registrations (with user + event hydrated) filtered
   * by the event-date period. Used by the summary dashboard to
   * compute KPIs / donut / occupancy / recent activity for the
   * active period (all time / one day / one year).
   *
   * - `period.kind: 'all'`  → no filter
   * - `period.kind: 'day'`  → only registrations whose event
   *   `event.date` falls on `period.date` (YYYY-MM-DD)
   * - `period.kind: 'year'` → only registrations whose event
   *   `event.date` is in the year `period.year`
   */
  listWithEventByPeriod(period: AttendancePeriod): Promise<RegistrationWithUserAndEvent[]>
}
