import type {
  Registration,
  RegistrationInput,
  RegistrationStatus,
  RegistrationWithEvent,
  RegistrationWithUser,
} from '~/domain/entities/registration'

export interface RegistrationListParams {
  eventId?: string
  userId?: string
  status?: RegistrationStatus
}

export interface RegistrationRepository {
  /**
   * Lists registrations. By default embeds `user:event_users(*)` so
   * the UI can render participant name and phone number directly.
   */
  getAll(params?: RegistrationListParams): Promise<RegistrationWithUser[]>

  getById(id: string): Promise<Registration | null>

  /**
   * Checks whether a user has already registered for a given event.
   * Used by the `BookEvent` use case to prevent duplicate inserts.
   */
  findByUserAndEvent(userId: string, eventId: string): Promise<Registration | null>

  /**
   * Inserts a new registration. The id is generated by the repository
   * ('REG-YYYY-NNNNN'). Throws when (userId, eventId) is duplicated
   * (unique constraint enforced at the DB level).
   */
  create(input: RegistrationInput): Promise<Registration>

  /**
   * Updates the registration status. Automatically sets
   * `checkin_at = now()` when the new status is 'Hadir', and clears
   * it when the status rolls back to 'Terdaftar'.
   */
  updateStatus(id: string, status: RegistrationStatus): Promise<Registration>

  delete(id: string): Promise<void>

  countByEvent(eventId: string): Promise<number>

  /**
   * Lists every registration of a user with the event relation
   * hydrated (`event:events(*)`). Result is sorted by `event.date`
   * descending, with `registered_at` descending as a tie-breaker.
   */
  listByUserWithEvent(userId: string): Promise<RegistrationWithEvent[]>
}
