-- =============================================================
-- Event Management System – Migration #3
-- Master category for events (`event_categories` + FK on `events`)
--
-- Run this in the Supabase SQL Editor:
--   https://app.supabase.com/project/_/sql
--
-- Notes:
-- - `event_categories.id` is TEXT with a custom format
--   `CAT-YYYY-NNNNN` (year + 5 digits), generated by the
--   application layer (the same pattern as `USR-…` and `REG-…`).
-- - `events.category_id` is NULLABLE and uses `ON DELETE RESTRICT`.
--   A category CANNOT be deleted while at least one event still
--   references it — admins must first reassign or delete those
--   events. The delete use case surfaces a friendly error when
--   the DB rejects the operation (FK violation 23503).
-- - RLS: public read, admin write (matches the existing
--   `events` and `event_users` policies).
-- =============================================================


-- -------------------------------------------------------------
-- 1. TABLE: event_categories
-- -------------------------------------------------------------
create table if not exists public.event_categories (
  id         text primary key,                          -- 'CAT-2026-00001'
  name       text not null unique,                      -- short label, e.g. 'Workshop'
  detail     text not null default '',                  -- optional long description
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Case-insensitive search index (helps the admin list page filter).
create index if not exists idx_event_categories_name
  on public.event_categories (lower(name));

-- Reuse the `set_updated_at()` trigger function from migration 001.
drop trigger if exists trg_event_categories_updated_at on public.event_categories;
create trigger trg_event_categories_updated_at
  before update on public.event_categories
  for each row execute function public.set_updated_at();


-- -------------------------------------------------------------
-- 2. ADD category_id TO events
-- -------------------------------------------------------------
-- RESTRICT (the default) blocks deleting a category that is still
-- referenced by any event. The application layer translates the
-- resulting FK violation into a human-readable error.
alter table public.events
  add column if not exists category_id text
    references public.event_categories(id) on delete restrict;

create index if not exists idx_events_category_id
  on public.events (category_id);


-- -------------------------------------------------------------
-- 3. ROW LEVEL SECURITY
-- -------------------------------------------------------------
alter table public.event_categories enable row level security;

-- Public read: anon + authenticated can list categories so the
-- home page card and the Add/Edit event modal can render the
-- category name and dropdown.
drop policy if exists "event_categories_read_public" on public.event_categories;
create policy "event_categories_read_public"
  on public.event_categories
  for select
  to anon, authenticated
  using (true);

-- Admin write: only authenticated users (admins, by convention)
-- can add / edit / delete categories.
drop policy if exists "event_categories_write_admin" on public.event_categories;
create policy "event_categories_write_admin"
  on public.event_categories
  for all
  to authenticated
  using (true)
  with check (true);
